# Generated by Django 4.2.22 on 2025-06-07 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingReminders', models.BooleanField(default=True)),
                ('timesheetReminders', models.BooleanField(default=True)),
                ('projectUpdates', models.BooleanField(default=True)),
                ('teamMentions', models.BooleanField(default=True)),
                ('reaveRequestStatus', models.BooleanField(default=True)),
                ('taskAssignments', models.BooleanField(default=True)),
                ('announcementUpdates', models.BooleanField(default=True)),
                ('emailAlerts', models.BooleanField(default=True)),
                ('smsAlerts', models.BooleanField(default=False)),
                ('pushNotifications', models.BooleanField(default=True)),
                ('browserNotifications', models.BooleanField(default=True)),
                ('desktopNotifications', models.BooleanField(default=False)),
                ('notificationSound', models.CharField(default='chime', max_length=20)),
                ('notificationVolume', models.IntegerField(default=50)),
                ('enableSoundAlerts', models.BooleanField(default=True)),
                ('dndMode', models.BooleanField(default=False)),
                ('dndFrom', models.TimeField(blank=True, null=True)),
                ('dndTo', models.TimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
