# Generated by Django 4.2.22 on 2025-06-07 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_usernotificationsetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileVisibility', models.CharField(default='everyone', max_length=20)),
                ('profilePictureVisibility', models.CharField(default='everyone', max_length=20)),
                ('contactVisibility', models.CharField(default='friends', max_length=20)),
                ('requestConnection', models.CharField(default='everyone', max_length=20)),
                ('followConnection', models.CharField(default='everyone', max_length=20)),
                ('suggestionsConnection', models.CharField(default='enabled', max_length=20)),
                ('messagePermission', models.CharField(default='friends', max_length=20)),
                ('mentionPermission', models.CharField(default='everyone', max_length=20)),
                ('lastSeenData', models.CharField(default='friends', max_length=20)),
                ('discoverableData', models.BooleanField(default=True)),
                ('activeStatusData', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
