# Generated by Django 4.2.22 on 2025-06-07 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('maritalstatus', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('counter', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileVisibility', models.CharField(max_length=20)),
                ('profilePictureVisibility', models.CharField(max_length=20)),
                ('contactVisibility', models.CharField(max_length=20)),
                ('requestConnection', models.CharField(max_length=20)),
                ('followConnection', models.CharField(max_length=20)),
                ('suggestionsConnection', models.CharField(max_length=20)),
                ('messagePermission', models.CharField(max_length=20)),
                ('mentionPermission', models.CharField(max_length=20)),
                ('lastSeenData', models.CharField(max_length=20)),
                ('discoverableData', models.BooleanField()),
                ('activeStatusData', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='username')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingReminders', models.BooleanField()),
                ('timesheetReminders', models.BooleanField()),
                ('projectUpdates', models.BooleanField()),
                ('teamMentions', models.BooleanField()),
                ('reaveRequestStatus', models.BooleanField()),
                ('taskAssignments', models.BooleanField()),
                ('announcementUpdates', models.BooleanField()),
                ('emailAlerts', models.BooleanField()),
                ('smsAlerts', models.BooleanField()),
                ('pushNotifications', models.BooleanField()),
                ('browserNotifications', models.BooleanField()),
                ('desktopNotifications', models.BooleanField()),
                ('notificationSound', models.CharField(max_length=20)),
                ('notificationVolume', models.IntegerField()),
                ('enableSoundAlerts', models.BooleanField()),
                ('dndMode', models.BooleanField()),
                ('dndFrom', models.TimeField()),
                ('dndTo', models.TimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.user', to_field='username')),
            ],
        ),
    ]
