# Generated by Django 4.2.22 on 2025-06-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='counter',
            new_name='country',
        ),
    ]
